### ISSUE TITLE
Where is the Fedora package?

### ISSUE THREAD

**Issue by ardevd** [jonasmalacofilho/liquidctl#108]
There doesnt seem to be any liquidctl for Fedora available and the Fedora package search link in the README returns 0 results. What gives?

**Comment by jonasmalacofilho** [comment]
@suve,

Can you tell what's happening?

I can still see it [here](https://src.fedoraproject.org/rpms/liquidctl), and the latest builds appear to have all succeeded.

Yet it's no longer listed on the [package search](https://apps.fedoraproject.org/packages/s/liquidctl).

**Comment by suve** [comment]
Installing the package from the command-line by using
```
dnf install liquidctl
```
works fine for me on both Fedora 31 and Fedora 32 beta.

I tried the package search and literally none of the packages I've added to Fedora in the last 2 years show up. **¯\\\_ツ\_/¯**

**Comment by jonasmalacofilho** [comment]
@suve,

Thanks for checking this!

Should we report the search bug to Fedora?

---

@ardevd,

Please let me know that installing from the command line worked for you.

**Comment by jonasmalacofilho** [comment]
Oh, it's already a know issue: fedora-infra/fedora-packages#432 ("Some packages can't be discovered").

**Comment by ardevd** [comment]
@jonasmalacofilho Thanks for figuring it out. The only reason I noticed this issue is because my fat fingers managed to mispell liquidctl when trying to install it which led me to check the package link in the README.

`dnf install liquidctl` works just fine :)

**Comment by jonasmalacofilho** [comment]
Ok, great.  Thanks for letting us know about the issue!

For now I changed the link in the README to the rpm source repository.
