### ISSUE TITLE
My NZXT RGB & Fan Controller device ID doesn't match the source code

### ISSUE THREAD

**Issue by bengl3rt** [jonasmalacofilho/liquidctl#110]
It looks like the source code expects:

(0x1e71, 0x2006, None, 'NZXT Smart Device V2 (experimental)'

However, I just connected the device and it shows up in lsusb on Linux as:

root@Echoplex:/tmp/liquidctl# lsusb | egrep NZXT
Bus 003 Device 002: ID 1e71:2009 NZXT NZXT USB Device

Everything else seems to work if I update the code accordingly.

**Comment by jonasmalacofilho** [comment]
Apparently NZXT's Ivan [misunderstood](https://www.reddit.com/r/NZXT/comments/erxk6v/introducing_the_new_rgb_fan_controller_from_nzxt/ff6odij) me back in January when I asket about whether the USB product ID would be kept the same.

Fixed in 'master'.  Thanks!
