### ISSUE TITLE
Add an "all fans" channel for the NZXT Smart Device

### ISSUE THREAD

**Issue by suve** [jonasmalacofilho/liquidctl#12]
I think it'd be nice to have a channel for controlling the speed of all fans at once in the Smart Device driver. This would eliminate the need to invoke `liquidctl` multiple times when one wants to keep all the fans at the same speed.

**Comment by jonasmalacofilho** [comment]
It is a good idea!  It should be easy to implement, why don't you give it a try?

Though I think we should call it `sync`, for uniformity with the existing option for syncing RGB channels of the Kraken coolers.

**Comment by jonasmalacofilho** [comment]
@suve I just noticed that it was you who got the packages for Fedora started.  Thanks!

What is the 'cannonical' URL for the Fedora packages?

One more thing: shouldn't `python3-liquidctl` require libusb-1.0 (package `libusbx`, I think)?

**Comment by suve** [comment]
What do you mean by "canonical URL"? The source repositories? Then I guess that'd be [`https://src.fedoraproject.org/rpms/liquidctl`](https://src.fedoraproject.org/rpms/liquidctl) for this one.

As for the dependencies, I admit I haven't looked at the full dependency list for the package and just trusted Fedora's `%{?python_enable_dependency_generator}` RPM macro to do its magic. I'll take a peek later today to ensure that `libusb` is among the dependencies.
