### ISSUE TITLE
X73 RGB Not working

### ISSUE THREAD

**Issue by kaaycraay** [jonasmalacofilho/liquidctl#120]
I have tried switching the usb around. I have tried deleted the device and restarting. Please help!!

**Comment by jonasmalacofilho** [comment]
Please clarify what you mean by "not working", what you are trying to do, which version of liquidctl you are using, and on which operating system you are.

**Comment by kaaycraay** [comment]
I plugged up everything for the AIO. I downloaded cam software. In CAM it see that i’m using a kraken X. However, when i’m trying to adjust the rgb lights it does not power on. I tried different connections of usb wires.

**Comment by kaaycraay** [comment]
I am currently using x64 NZXT Kraken X73

**Comment by jonasmalacofilho** [comment]
I'm sorry, you're using CAM, not liquidctl?

Why are you posting here then?

**Comment by kaaycraay** [comment]
Sorry, did not noticed. Is liquidctl a software you can use to control kraken x73? Change RGB?


Sent from Yahoo Mail for iPhone


On Monday, June 1, 2020, 7:51 AM, Jonas Malaco <notifications@github.com> wrote:




I'm sorry, you're using CAM, not liquidctl?

Why are you posting here then?

**Comment by jonasmalacofilho** [comment]
An experimental driver for it was just merged this weekend, after almost two months of development.

---

But what you describe could suggest (among other things) a hardware problem: CAM recognizes the device but isn't able to control it.

> **In CAM it see that i’m using a kraken X.** However, when i’m trying to adjust the rgb lights it does not power on.

I recommend you get that sorted first (by reaching out to NZXT) before trying out liquidctl.

**Comment by kaaycraay** [comment]
Thank you for the information! 


Sent from Yahoo Mail for iPhone


On Monday, June 1, 2020, 8:29 AM, Jonas Malaco <notifications@github.com> wrote:




An experimental driver for it was just merged this weekend, after almost two months of development.

But what you describe could suggest (among other things) a hardware problem: CAM recognizes the device but isn't able to control it.


In CAM it see that i’m using a kraken X. However, when i’m trying to adjust the rgb lights it does not power on.


I recommend you get that sorted first (by reaching out to NZXT) before trying out liquidctl.
