### ISSUE TITLE
no list devices

### ISSUE THREAD

**Issue by Niil78** [jonasmalacofilho/liquidctl#133]
Hi, i try install liquidctl on my arch, and no list devices:
lsusb >
Bus 002 Device 004: ID 1b1c:0c18 Corsair H100i Platinum
liquidctl initialize
No devices matches available drivers and selection criteria
and list no show devices

**Comment by audiohacked** [comment]
Support for the H100i Platinum can only be found in the `corsair-platinum-coolers` branch. Both Arch Linux packages found on AUR, build against the master branch.

**Comment by jonasmalacofilho** [comment]
@Niil78 

To test the Platinum collers edit the PKGBUILD of `liquidctl-git` before the usual `makepkg -si`:

```patch
-source=("$pkgname::git+https://github.com/jonasmalacofilho/liquidctl.git#branch=master")
+source=("$pkgname::git+https://github.com/jonasmalacofilho/liquidctl.git#branch=corsair-platinum-coolers")
```

**Comment by Niil78** [comment]
Sorry, but where found;
source=("$pkgname::git+https://github.com/jonasmalacofilho/liquidctl.git#branch=master
i now use pakku for install and edit. but no see the line. 
sorry :/

**Comment by Niil78** [comment]
> Support for the H100i Platinum can only be found in the `corsair-platinum-coolers` branch. Both Arch Linux packages found on AUR, build against the master branch.
i try search on aur whit Yay and pakku and no see thats packages. :/
OpencorsairLink now cant install on my arch. but when i use work for me. ;)

**Comment by audiohacked** [comment]
@Niil78 The base `liquidctl` PKGBUILD downloads a release `tar.gz` so there's no way to set the branch. You must use the `liquidctl-git` PKGBUILD and modify it.

**Comment by jonasmalacofilho** [comment]
Here's the link to [liquidctl-git<sup>AUR</sup>](https://aur.archlinux.org/packages/liquidctl-git/).

**Comment by Niil78** [comment]
Yesh! now work.! 
$ liquidctl list
Device ID 0: Corsair H100i Platinum (experimental)

**Comment by Niil78** [comment]
one thing more. sorry for re up this,
when i try use; [https://github.com/jonasmalacofilho/liquidctl/blob/master/docs/asetek-690lc.md](url)
when y try configure, all time get that error.
~ $ liquidctl set fan speed 20 0 40 100
ERROR: Unexpected error with Corsair H100i Platinum (experimental)
Traceback (most recent call last):
NotImplementedError

normally work great (the liquid ref) I don't need to configure it, but I would like to know what I can do with the application.

Thanx

**Comment by jonasmalacofilho** [comment]
@Niil78 

Profiles haven't been implemented on the new driver yet.

P.S. The documentation you've linked to is _not_ related to the H100i Platinum.
