### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DumbQuestion** [jonasmalacofilho/liquidctl#141]
In the command:

```
# liquidctl set fan speed temp duty
```

What temperature does temp refer to?  Is it the cpu temp or one of the temps on the motherboard.
Thanks for answering this.

**Comment by jonasmalacofilho** [comment]
This commands sets a profile to run on the cooler, that is, without constant updates from the software.

For this the device must have access to the sensor; in all cases (so far) the internal liquid temperature probe is used.

---

Software-based profiles are being worked on (you can follow the progress in #72; and you can find some scripts in `extra/` that already experiment with this).

But for devices that have internal sensors, that's generally a much better solution: having the device execute the profile independently of any software or even operating system is a lot more robust; additionally, from a thermodynamic point of view, it makes more sense to control radiator fans based on the temperature of the liquid (at least with simple curves... PID control would be a totally different case).
