### ISSUE TITLE
Support for H150i Platinum

### ISSUE THREAD

**Issue by shaelr** [jonasmalacofilho/liquidctl#146]
Would it be possible to add support for this device id?
0x0c12

**Comment by jonasmalacofilho** [comment]
We have already started to work on this, and the driver requires a few adjustments.  You can follow the progress (or maybe claim this task for yourself) in #138.

**Comment by shaelr** [comment]
different device id's... appreciate the help

**Comment by jonasmalacofilho** [comment]
I missed that, sorry!  Well, but "you" _(or rather Corsair)_ tricked me: your device is a H150i PRO, not Platinum ; )

Please see/follow #137 then.  TL; DR: pull requests are encouraged, possibly from porting the code in OpenCorsairLink.

**Comment by shaelr** [comment]
got it. thanks! i will follow along there.
