### ISSUE TITLE
Need liquidctl to work with EVGA CLC 280 AIO

### ISSUE THREAD

**Issue by KeithMyers** [jonasmalacofilho/liquidctl#16]
I think that the NZXT AIO's use Asetek hardware like the EVGA.  So is it possible to get support for the EVGA CLC 280?

I just put this onto one of my 2700X Linux hosts because my normal choice for the Corsair H110i was not available.  I am thinking I made a big mistake.  The H110i runs the pump at full speed off SATA power.

I have the CLC 280 hooked to the AIO header with disabled control which should give it 12V for full speed.  But I am only getting 1400 rpm out of the pump and my radiator temps are not good.

**Comment by jonasmalacofilho** [comment]
Yes, I would like to support it.

Check my last comment on #

**Comment by jonasmalacofilho** [comment]
Yes, I'm planning to support it together with the second generation Krakens.

Please check (my last comment on) #3 for status and instructions on how/what to test.

---

Answering from my phone and accidentally closed the issue.  Already reopened it.

**Comment by bmuzika** [comment]
I can get some Wireshark captures in an hour or two. Is there anything in particular that you need me to grab?

**Comment by KeithMyers** [comment]
This is my lusb printout for my EVGA CLC 280
keith@Serenity:~$ sudo lsusb -v -d 2433:b200
[sudo] password for keith: 

Bus 001 Device 005: ID 2433:b200  
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x2433 
  idProduct          0xb200 
  bcdDevice            1.00
  iManufacturer           1 ASETEK
  iProduct                2 690LC
  iSerial                 3 CCVI_1.0
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           32
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower               50mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
Device Status:     0x0000
  (Bus Powered)
keith@Serenity:~$ 


I'll try some of your commits to see what I can control.  All I'm really interested in is getting pump speed up to 100%.  I set the fans via BIOS for full speed all the time.

**Comment by KeithMyers** [comment]
I'm going to need some help in installing and running the program it seems.  None of the proffered installation programs succeeded.
keith@Serenity:~/liquidctl$ pip install liquidctl
Collecting liquidctl
  Could not find a version that satisfies the requirement liquidctl (from versions: )
No matching distribution found for liquidctl

So I just cloned the repository but I still can't run anything.

keith@Serenity:~/liquidctl$ python setup.py
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    with open('README.md', 'r', encoding='utf-8') as fh:
TypeError: 'encoding' is an invalid keyword argument for this function

I installed the pip environment.  I run other python programs without issue.  Any help here?

**Comment by jonasmalacofilho** [comment]
@bmuzika that's great.  I think right now I need a _fresh_ picture of how the device operates.  Maybe there's something interesting or useful that Flow Control does differently than CAM.

Besides captures of all features available in software being applied (or possibly being *re*applied), these are my particular areas of interest/concern:

 - what messages are – _over time/after your configuration has been applied_ – sent to the device (i.e. commands) before it responds (i.e. status)
 - the connection procedure (i.e. what happens when Flow Control first opens)
 - the disconnection procedure (i.e. what happens when it is closed)

One thing you might need to watch out for is that other software on Windows might try to access the device and mess up these details in the captures.  The most obvious candidates for this are CorsairLink, iCue, Cam, HWiNFO and SIV.

Also, if you can, try #7 (Support for Asetek 690LC coolers) and see if you can debug any issues you find on the spot, since you have the device and Wireshark open : )

**Comment by jonasmalacofilho** [comment]
@KeithMyers thanks!

The first thing that comes to mind is that you might have Python 2 installed and `pip` and `python` are pointing to that version.  You need make sure to use Python 3 and a compatible pip version.

**Comment by KeithMyers** [comment]
Synaptic says I have python 3.6 installed.  But python --version tells me different.

keith@Serenity:~/Downloads/Utils/liquidctl-add-second-gen-krakens$ python --version
Python 2.7.15rc1

**Comment by jonasmalacofilho** [comment]
That's normal.  Try `pip3`?

(disclaimer: can't remember for sure if that's how things are set up on Ubuntu)

**Comment by KeithMyers** [comment]
keith@Serenity:~/Downloads/Utils/liquidctl-add-second-gen-krakens$ python3 setup.py
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    import setuptools
ModuleNotFoundError: No module named 'setuptools'

**Comment by KeithMyers** [comment]
Installed python3 setuptools.  Making some progress.
keith@Serenity:~/Downloads/Utils/liquidctl-add-second-gen-krakens$ python3 setup.py
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

**Comment by jonasmalacofilho** [comment]
I think that one was my bad, apparently for setuptools you need to add the `install` command:

```
python3 setup.py install
```

**Comment by KeithMyers** [comment]
Ok.  Now making real progress.

root@Serenity:/home/keith/Downloads/Utils/liquidctl-add-second-gen-krakens# python3 setup.py install
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
creating liquidctl.egg-info
writing liquidctl.egg-info/PKG-INFO
writing dependency_links to liquidctl.egg-info/dependency_links.txt
writing entry points to liquidctl.egg-info/entry_points.txt
writing requirements to liquidctl.egg-info/requires.txt
writing top-level names to liquidctl.egg-info/top_level.txt
writing manifest file 'liquidctl.egg-info/SOURCES.txt'
reading manifest file 'liquidctl.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'liquidctl.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/liquidctl
copying liquidctl/version.py -> build/lib/liquidctl
copying liquidctl/__init__.py -> build/lib/liquidctl
copying liquidctl/cli.py -> build/lib/liquidctl
copying liquidctl/util.py -> build/lib/liquidctl
creating build/lib/liquidctl/driver
copying liquidctl/driver/__init__.py -> build/lib/liquidctl/driver
copying liquidctl/driver/kraken_two.py -> build/lib/liquidctl/driver
copying liquidctl/driver/base_usb.py -> build/lib/liquidctl/driver
copying liquidctl/driver/asetek.py -> build/lib/liquidctl/driver
copying liquidctl/driver/nzxt_smart_device.py -> build/lib/liquidctl/driver
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/liquidctl
copying build/lib/liquidctl/version.py -> build/bdist.linux-x86_64/egg/liquidctl
copying build/lib/liquidctl/__init__.py -> build/bdist.linux-x86_64/egg/liquidctl
copying build/lib/liquidctl/cli.py -> build/bdist.linux-x86_64/egg/liquidctl
creating build/bdist.linux-x86_64/egg/liquidctl/driver
copying build/lib/liquidctl/driver/__init__.py -> build/bdist.linux-x86_64/egg/liquidctl/driver
copying build/lib/liquidctl/driver/kraken_two.py -> build/bdist.linux-x86_64/egg/liquidctl/driver
copying build/lib/liquidctl/driver/base_usb.py -> build/bdist.linux-x86_64/egg/liquidctl/driver
copying build/lib/liquidctl/driver/asetek.py -> build/bdist.linux-x86_64/egg/liquidctl/driver
copying build/lib/liquidctl/driver/nzxt_smart_device.py -> build/bdist.linux-x86_64/egg/liquidctl/driver
copying build/lib/liquidctl/util.py -> build/bdist.linux-x86_64/egg/liquidctl
byte-compiling build/bdist.linux-x86_64/egg/liquidctl/version.py to version.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/liquidctl/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/liquidctl/cli.py to cli.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/liquidctl/driver/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/liquidctl/driver/kraken_two.py to kraken_two.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/liquidctl/driver/base_usb.py to base_usb.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/liquidctl/driver/asetek.py to asetek.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/liquidctl/driver/nzxt_smart_device.py to nzxt_smart_device.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/liquidctl/util.py to util.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying liquidctl.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying liquidctl.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying liquidctl.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying liquidctl.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying liquidctl.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying liquidctl.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/liquidctl-1.2.0.dev0-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing liquidctl-1.2.0.dev0-py3.6.egg
Copying liquidctl-1.2.0.dev0-py3.6.egg to /usr/local/lib/python3.6/dist-packages
Adding liquidctl 1.2.0.dev0 to easy-install.pth file
Installing liquidctl script to /usr/local/bin

Installed /usr/local/lib/python3.6/dist-packages/liquidctl-1.2.0.dev0-py3.6.egg
Processing dependencies for liquidctl==1.2.0.dev0
Searching for pyusb
Reading https://pypi.python.org/simple/pyusb/
Downloading https://files.pythonhosted.org/packages/5f/34/2095e821c01225377dda4ebdbd53d8316d6abb243c9bee43d3888fa91dd6/pyusb-1.0.2.tar.gz#sha256=4e9b72cc4a4205ca64fbf1f3fff39a335512166c151ad103e55c8223ac147362
Best match: pyusb 1.0.2
Processing pyusb-1.0.2.tar.gz
Writing /tmp/easy_install-7nlyw3x4/pyusb-1.0.2/setup.cfg
Running pyusb-1.0.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-7nlyw3x4/pyusb-1.0.2/egg-dist-tmp-nsul8t7l
warning: no files found matching 'ReleaseNotes.rst'
zip_safe flag not set; analyzing archive contents...
Moving pyusb-1.0.2-py3.6.egg to /usr/local/lib/python3.6/dist-packages
Adding pyusb 1.0.2 to easy-install.pth file

Installed /usr/local/lib/python3.6/dist-packages/pyusb-1.0.2-py3.6.egg
Searching for docopt
Reading https://pypi.python.org/simple/docopt/
Downloading https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz#sha256=49b3a825280bd66b3aa83585ef59c4a8c82f2c8a522dbe754a8bc8d08c85c491
Best match: docopt 0.6.2
Processing docopt-0.6.2.tar.gz
Writing /tmp/easy_install-jpqng2wa/docopt-0.6.2/setup.cfg
Running docopt-0.6.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-jpqng2wa/docopt-0.6.2/egg-dist-tmp-fmweuo4_
zip_safe flag not set; analyzing archive contents...
Moving docopt-0.6.2-py3.6.egg to /usr/local/lib/python3.6/dist-packages
Adding docopt 0.6.2 to easy-install.pth file

Installed /usr/local/lib/python3.6/dist-packages/docopt-0.6.2-py3.6.egg
Finished processing dependencies for liquidctl==1.2.0.dev0
root@Serenity:/home/keith/Downloads/Utils/liquidctl-add-second-gen-krakens#

**Comment by KeithMyers** [comment]
So, where am I at now?  What is needed next to run the liquidctl program?

**Comment by KeithMyers** [comment]
Do you have any idea of the pipe error?  Googling didn't have anything jump out at me on how to resolve.

Benign for now as I can get the status of the device.  Still would like to know who is correct or pump speed, the liquidctl status probe or the Asus wmi sensor driver.

All the other Asus WMI sensor values match what it shown in the BIOS.  Also wanted to make clear the BIOS AIO speed shows 1440 rpm for that sensor.  So if the BIOS does not have it correct at half speed, expect what the BIOS exports through the WMI interface to be the same.

Does your liquidctl application directly probe the pump hardware?  Or is it interpreted through scaling?

**Comment by bmuzika** [comment]
I have tried to get some captures from Flow Control. I ran it in a Windows 10 VM on an openSUSE host. 

I'm not sure if these are useful or not. I can try to capture again from within Windows (natively) if these don't work out.


[Wireshark Captures.zip](https://github.com/jonasmalacofilho/liquidctl/files/2825078/Wireshark.Captures.zip)

**Comment by KeithMyers** [comment]
I'll tackle this commit tomorrow and see what the warnings look like.  Needed to put the host back to crunching.

**Comment by jonasmalacofilho** [comment]
@KeithMyers 

> failed to (pre) open ([Errno 32] Pipe error), but continuing

This is a warning I inserted to figure out whether these devices needed a particular set of extra initialization instructions.  _Apparently_ not...  I just updated the branch to make these warnings less intrusive (and they should be completely gone by the time this feature gets merged).

After you update, can you try `liquidctl status --debug` _once_ and send me the output?  I want to double check that this device doesn't need (or support) this entire part of the initialization code.

---

> Interesting that your program is reporting the pump rpm at 2880 rpm. That is twice the rpm that the ASUS-WMI-SENSORS driver is reporting for the AIO header speed.

> Still would like to know who is correct for pump speed, the liquidctl status probe or the Asus wmi sensor driver.

> Does your liquidctl application directly probe the pump hardware? Or is it interpreted through scaling?

liquidctl probes the largest controller which is responsible for all communication, configuration and aestetics.  That chip is supposed to and correctly interpret the tachometer pulses from the pump.

Having a halved speed for AIO pumps in the BIOS is commonplace, but I'm not sure if that applies to this specific model.  Have you checked for similar reports (between Flow Control and BIOS) on the EVGA forums?

---

> Fan speed 0 rpm

Aren't you running your fans from the cooler?

**Comment by KeithMyers** [comment]
No I haven't looked in the EVGA forums for what BIOS and Windows reporting programs report. I need to do that.

No, I am using the motherboard CPU Fan header to control the fans on the radiator.  I went with some ML140 fans I had on the shelf because I had no experience with the weird EVGA shrouded fans and I could find no information on them in the forums regarding their bearings or max fan speed.  I know the ML-140 fans  well as I use them everywhere on my hosts.

**Comment by jonasmalacofilho** [comment]
@bmuzika I started analyzing the captures; I'll post an update when I'm done (might be tomorrow evening).

@KeithMyers, funny fact: from the captures bmuzika supplied I can see that Flow Control attemps the same extra initialization procedures as I do, and also gets the same same failures.

**Comment by jonasmalacofilho** [comment]
@KeithMyers I'm not familiar with GKrelim; _if it uses libsensors,_ you could try a `compute` directive (see `man sensors.conf`).

I only mentioned the fans because their speed was being reported as zero, and I would like to confirm that field is being correctly read as well.

**Comment by KeithMyers** [comment]
And it didn't work as I expected.

**Comment by jonasmalacofilho** [comment]
Let's keep this discussion on topic, someone else is part of the thread and I don't want to spam him them.

Reach out to me on [gitter](https://gitter.im/liquidctl/Lobby) or by email (address listed on my GitHub profile) and I'll help with configuring libsensors.

**Comment by jonasmalacofilho** [comment]
@bmuzika, thanks again for supplying those captures.  I added my analysis to [#7/docs/development/asetek690lc/evga-clc-capture-1.txt](https://github.com/jonasmalacofilho/liquidctl/blob/add-second-gen-krakens/docs/development/asetek690lc/evga-clc-capture-1.txt).

I think was able to make out most of it, but I could use another capture session while you change different settings one by one, keeping note of the order of changes (type, values).

There were also a few requests I could not understand at all.  The ones during the connection phase probably don't matter, but the other two (`0x2303` midway and `0x21` before disconnecting) might be relevant.  If you spot them on future captures, see if you can figure out what changes trigger them.

**Comment by bmuzika** [comment]
@jonasmalacofilho I just realized that I forgot to include one of my captures from that session. I'm attaching that here. 

In this capture, I believe that I set the fans to max speed, then min speed, then max speed again. I'll do another round of captures again tomorrow (Sunday) with better details captured.

[fan_max-min-max_only_clc.zip](https://github.com/jonasmalacofilho/liquidctl/files/2848576/fan_max-min-max_only_clc.zip)

**Comment by jonasmalacofilho** [comment]
@bmuzika thanks again!

I just updated my notes with the additional data (commit 6409010b92d0bfc218861cb9941542b0ee2fb694).

**Comment by jonasmalacofilho** [comment]
The current state of the 'master' branch should already support these EVGA CLCs quite decently, so I'll close this issue.  @KeithMyers and @bmuzika, thanks for your collaboration.

Documentation is still lacking for the new driver, so I'll quickly enumerate the supported features and options:

---

The device must be initialized after every boot.  After that you can query the device status and perform other operations.

```
liquidctl initialize
liquidctl status
```

Fan speeds can be configured either by fixed duty values or (temperature, duty) profiles.  The profiles accept up to six points, and are interpolated by the device.

```
liquidctl set fan speed 50
liquidctl set fan speed 20 0 40 100
```

Pump speeds, on the other hand, only accept fixed duty values.

```
liquidctl set pump speed 75
```

There's a single lighting channel; no particular name is enforced yet, but I'll use 'logo' in these examples. 
 The first light mode – 'rainbow' – supports an abstract `--speed` parameter, varying from 1 to 6.

```
liquidctl set logo color rainbow
liquidctl set logo color rainbow --speed 1
liquidctl set logo color rainbow --speed 6
```

The 'fading' mode supports specifying the `--time-per-color` in seconds (the default is 1 second per color).

```
liquidctl set logo color fading ff8000 00ff80
liquidctl set logo color fading ff8000 00ff80 --time-per-color 2
```

The 'blinking' mode accepts both `--time-per-color` and `--time-off` (also in seconds).  The default is 1 second for each, and whenever unspecified `--time-off` will equal `--time-per-color`.

```
liquidctl set logo color blinking 8000ff
liquidctl set logo color blinking 8000ff --time-off 2
liquidctl set logo color blinking 8000ff --time-per-color 2
liquidctl set logo color blinking 8000ff --time-per-color 2 --time-off 1
```

Finally, the cooler supports two more lighting modes: 'fixed' and 'blackout'.  The latter is the only one to completely turn off the LED; however, it also inhibits the visual high-temperature alert.

```
liquidctl set logo color fixed 00ff00
liquidctl set logo color blackout
```
