### ISSUE TITLE
USB Error

### ISSUE THREAD

**Issue by AntiBasti** [jonasmalacofilho/liquidctl#169]
Hi, i can't get the programm to work with my Kraken. This is the debug output:

DEBUG] liquidctl.cli: running liquidctl v1.4.0 (Arch User Repository; liquidctl-git 1.4.0.r17.95b326a-1)
[DEBUG] liquidctl.driver.usb: searching HidapiBus (api=hid, drivers=[CorsairHidPsu, HydroPlatinum, Kraken2, KrakenX3, KrakenZ3, NzxtEPsu, RgbFusion2, SmartDevice, SmartDevice2, _CommonSmartDeviceDriver])
[DEBUG] liquidctl.driver.usb: probing drivers for device 3057:0001
[DEBUG] liquidctl.driver.usb: probing drivers for device 1b1c:1b48
[DEBUG] liquidctl.driver.usb: probing drivers for device 1b1c:1b48
[DEBUG] liquidctl.driver.usb: probing drivers for device 048d:8297
[DEBUG] liquidctl.driver.usb: instanced driver for Gigabyte RGB Fusion 2.0 8297 Controller (experimental)
[DEBUG] liquidctl.driver.usb: searching PyUsbBus (drivers=[Hydro690Lc, Legacy690Lc, Modern690Lc, _CommonAsetekDriver])
[DEBUG] liquidctl.driver.usb: probing drivers for device 04e8:61f6
[DEBUG] liquidctl.driver.usb: probing drivers for device 1d6b:0003
[DEBUG] liquidctl.driver.usb: probing drivers for device 2a39:3fb0
[DEBUG] liquidctl.driver.usb: probing drivers for device 8087:0aaa
[DEBUG] liquidctl.driver.usb: probing drivers for device 2433:b200
[DEBUG] liquidctl.driver.usb: instanced driver for Asetek 690LC (assuming EVGA CLC)
[DEBUG] liquidctl.driver.usb: probing drivers for device 05e3:0608
[DEBUG] liquidctl.driver.usb: probing drivers for device 048d:8297
[DEBUG] liquidctl.driver.usb: probing drivers for device 1b1c:1b48
[DEBUG] liquidctl.driver.usb: probing drivers for device 3057:0001
[DEBUG] liquidctl.driver.usb: probing drivers for device 05e3:0608
[DEBUG] liquidctl.driver.usb: probing drivers for device 1d6b:0002
[DEBUG] liquidctl.cli: device: Gigabyte RGB Fusion 2.0 8297 Controller (experimental)
[INFO] liquidctl.driver.rgb_fusion2: Status reports not available from Gigabyte RGB Fusion 2.0 8297 Controller (experimental)
[DEBUG] liquidctl.cli: device: Asetek 690LC (assuming EVGA CLC)
[DEBUG] liquidctl.driver.usb: selected interface: 0
[DEBUG] liquidctl.driver.asetek: set clear to send = True
[DEBUG] liquidctl.driver.usb: sending control transfer with (64, 2, 2), {}
[DEBUG] liquidctl.driver.asetek: begin transaction
[DEBUG] liquidctl.driver.usb: explicitly claim interface
[DEBUG] liquidctl.driver.usb: sending control transfer with (64, 2, 1), {}
[DEBUG] liquidctl.driver.usb: writting 4 bytes: 14:00:00:00
[ERROR] liquidctl.cli: Unexpected error with Asetek 690LC (assuming EVGA CLC)
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/liquidctl/cli.py", line 302, in main
    _print_dev_status(dev, dev.get_status(**opts))
  File "/usr/lib/python3.8/site-packages/liquidctl/driver/asetek.py", line 192, in get_status
    msg = self._end_transaction_and_read()
  File "/usr/lib/python3.8/site-packages/liquidctl/driver/asetek.py", line 107, in _end_transaction_and_read
    msg = self.device.read(_READ_ENDPOINT, _READ_LENGTH, _READ_TIMEOUT)
  File "/usr/lib/python3.8/site-packages/liquidctl/driver/usb.py", line 278, in read
    data = self.usbdev.read(endpoint, length, timeout=timeout)
  File "/usr/lib/python3.8/site-packages/usb/core.py", line 983, in read
    ret = fn(
  File "/usr/lib/python3.8/site-packages/usb/backend/libusb1.py", line 828, in bulk_read
    return self.__read(self.lib.libusb_bulk_transfer,
  File "/usr/lib/python3.8/site-packages/usb/backend/libusb1.py", line 936, in __read
    _check(retval)
  File "/usr/lib/python3.8/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 110] Operation timed out
[DEBUG] liquidctl.driver.usb: ensure interface is released

Any ideas guys? :)

**Comment by jonasmalacofilho** [comment]
You were missing the `--legacy-690lc` flag.

> **Note: when dealing with legacy Krakens the --legacy-690lc flag should be supplied on all invocations of liquidctl.**
> —_Guide for using liquidctl with [Asetek 690LC liquid coolers](https://github.com/jonasmalacofilho/liquidctl/blob/master/docs/asetek-690lc-guide.md#asetek-690lc-liquid-coolers), linked from the list of supported devices_

Unfortunately there are at least two significantly different and incompatible types of these coolers, and there is no way of identifying which is the appropriate mode for a particular device.

Both use the exact same identifiers (which, by the way, are for a general-purpose hardware development kit), and the type we call "legacy" usually needs to be restarted after a "modern" command is sent to it.

This is why you probably also want to power down the system and restart the cooler's embedded controller.
