### ISSUE TITLE
Cannot install on Linux Mint 20 - getting "cannot find -ludev" while trying to install via pip3

### ISSUE THREAD

**Issue by luso7214** [jonasmalacofilho/liquidctl#207]
I've been trying to install this repo through pip3 on linux mint and I can't seem to get it to complete without getting an error "cannot find -ludev". Has anyone else encountered this error? 

<img width="1732" alt="Screen Shot 2020-10-25 at 12 25 02 PM" src="https://user-images.githubusercontent.com/73442262/97116883-83280480-16bd-11eb-9bc5-a37e11c4529a.png">

**Comment by jonasmalacofilho** [comment]
If cython-hidapi is installed from PyPI, then build tools and development headers for Python, libusb-1.0 and libudev are also needed.

**Comment by jonasmalacofilho** [comment]
Oh, on Mint these development headers for libudev are probably in a package called libudev-dev.
