### ISSUE TITLE
liquidctl doesn't detect my x72

### ISSUE THREAD

**Issue by wqkl** [jonasmalacofilho/liquidctl#211]
Running a 5600x on x72, liquidctl doesn't detect the x72 usb
![image](https://user-images.githubusercontent.com/39051798/98460844-50602f00-21da-11eb-8b22-86b413e8a5a5.png)

**Comment by wqkl** [comment]
Here is another screenshot I took earlier
https://imgur.com/a/1zY2kVh

**Comment by jonasmalacofilho** [comment]
You need to restore the original driver (Microsoft Generic HID Driver).

You can find more information about when to use custom drivers, and when not to, in the README, specifically in the list of supported devices and in the Windows and Troubleshooting sections.

**Comment by wqkl** [comment]
I have changed it to WinUSB, yet it still doesn't detect it, sorry still learning python in campus
![image](https://user-images.githubusercontent.com/39051798/98466106-fd00d780-21ff-11eb-9dd8-ff08ab88f6ae.png)

**Comment by jonasmalacofilho** [comment]
You need to uninstall the custom driver, and let Windows restore a default one.  The X72 is a USB HID, and liquidctl uses [HIDAPI](https://github.com/libusb/hidapi) to communicate with HIDs; but this only works with the (original) Microsoft Generic HID Driver.
