### ISSUE TITLE
Dependence needed for ubuntu

### ISSUE THREAD

**Issue by redno2** [jonasmalacofilho/liquidctl#238]
Hi, 
on the latest ubuntu 20.04 your need to add these libs as a dependence which is not installed by default, to install liquidctl with pip3.

`sudo apt install libusb-1.0-0-dev libudev-dev `

May be interesting to add it in your documentation.

thanks.

**Comment by jonasmalacofilho** [comment]
Thanks!

It's already in the documentation though.

> If cython-hidapi is installed from sources or directly from PyPI, then build tools and development headers for Python, libusb-1.0 and libudev are also needed.
—https://github.com/jonasmalacofilho/liquidctl#installing-on-linux
