### ISSUE TITLE
Grid+ V3 Duty Cycle

### ISSUE THREAD

**Issue by Cheata** [jonasmalacofilho/liquidctl#28]
I note that for the Grid+ V3 Fan speeds can only be set to fixed duty values. Is this a limitation of the Grid+ or do you have plans to allow speed scaling based on temperature?

**Comment by jonasmalacofilho** [comment]
Yes, the Grid+ has no temperature sensors, nor on-device profiles.

You could try to pick where we stopped in #8 ("Providing fan and pump curves for ~the older firmware X62s~ devices without native support for them").  The idea is to implement a software daemon that repeatedly adjusts the devices' speeds based on a selected temperature sensor.

This would also allow to control liquidctl devices based on CPU and GPU core temperatures (assuming you can programatically access those sensors).
