### ISSUE TITLE
How to use a testing branch for getting news features which are not yet available in stable version

### ISSUE THREAD

**Issue by olielvewen** [jonasmalacofilho/liquidctl#40]
Hi Jonas,

I am sure that this question will interest a lot of people who are using liquidctl and even for others projects.

How to use a testing branch for getting news features which are not yet available in the stable version knowing that they have already the stable version of liquidctl installed and that this testing branch must propose a clean experience (i.e do not put the mess in the system ) ?

What did you advice ?

**Comment by jonasmalacofilho** [comment]
For others arriving here:

 - manually install from git or a source tarball using setuptools, possibly in a virtual environment
 - install from git or a source tarball using pip, also possibly in a virtual environment
 - on ArchLinux adapt the PKGBUILD in [python-liquidctl-git<sup>AUR</sup>](https://aur.archlinux.org/packages/python-liquidctl-git/) to point to the desired branch
 - on Windows checkout the pre-built executables on our AppVeyor CI

**Comment by olielvewen** [comment]
>First, there are too many definitions for what a "clean" workflow can be, and too many use cases (e.g. trying a custom branch in parallel; quickly pulling a fix; helping with a new driver; developing a new driver).

Indeed, I agree that was not clear. My idea was for trying a custom branch in parallel.

>I think this will help you: python-liquidctl-gitAUR.

Just edit the branch name ; )

The fact of having to create a branch based on the commits is a very good thing that the future contributors / beta testers will appreciate.
And the fact to be on Archlinux and derivated like us is a huge help and so simple.
Great work.

**Comment by jonasmalacofilho** [comment]
Btw @olielvewen , thanks for (unknowingly) pushing me into using PKGBUILDs myself.

I did say _"for the software I contribute to, that's just not ideal",_ but since then I've been a private `python-liquidctl-local` PKGBUILD and life is indeed better, even if a tiny bit more cumbersome.

Thanks again!
