### ISSUE TITLE
setup.py install_requires is missing cython

### ISSUE THREAD

**Issue by leinardi** [jonasmalacofilho/liquidctl#49]
While packaging version 1.2.0 of liquidctl in a flatpak I noticed that the dependency on cython missing (I had to manually install it).

**Comment by jonasmalacofilho** [comment]
I think this should be reported to [cython-hidapi](https://github.com/trezor/cython-hidapi), as Cython is only necessary to build it.

**Comment by jonasmalacofilho** [comment]
Note that in cython-hidapi Cython is already listed in setup_requires, but evidently that's not enough.  Be sure to include the build log showing that (it isn't enough) when reporting the bug there.

I'll close this issue, but please let me know if you think there's anything else I should do about this in liquidctl.
