### ISSUE TITLE
FYI - I was able to build this on Void Linux

### ISSUE THREAD

**Issue by Frick-David** [jonasmalacofilho/liquidctl#90]
Just FYI, I was able to build and use this on void linux. I just had to install python3-devel to get it to work, but the respective dependencies packages for void linux are:
```
python3
libusb
python3-setuptools
python3-docopt
python3-usb
python3-devel  (for hidapi)
```

See [this issue](https://github.com/void-linux/void-packages/issues/19670#issuecomment-593963982). I asked if they can package it for void linux.

Pretty cool! Hope all is well!

**Comment by jonasmalacofilho** [comment]
That's great news, thanks!

Let me know if/when a liquidctl package for void linux is available so I can update the readme.

**Comment by jonasmalacofilho** [comment]
I'm closing this as there's nothing to do on this side, but I'm anxious to see liquidctl available in Void Linux.

**Comment by Frick-David** [comment]
I will ask the void linux people to package it!

-------- Original Message --------
On Mar 25, 2020, 6:39 PM, Jonas Malaco < notifications@github.com> wrote:
I'm closing this as there's nothing to do on this side, but I'm anxious to see liquidctl available in Void Linux.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[https://github.com](<a href=)/jonasmalacofilho/liquidctl/issues/90#issuecomment-604124498">https://github.com/jonasmalacofilho/liquidctl/issues/90#issuecomment-604124498", "url": "[https://github.com](<a href=)/jonasmalacofilho/liquidctl/issues/90#issuecomment-604124498">https://github.com/jonasmalacofilho/liquidctl/issues/90#issuecomment-604124498", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by jonasmalacofilho** [comment]
Great, thanks!
